spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/my_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: poqwer95
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

mybatis:
  type-aliases-package: com.review.mybatis
  mapper-locations: static/mapper/*.xml